### ISSUE TITLE
Data Importing & Vetting features in IFs

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#245] opened 2023-08-28 16:56 UTC
Some more issues we discovered during the data vetting process, 

1. When we do comparisons between newly imported tables and existing tables in IFs, some existing tables are not properly loaded. You can see that in the screenshot below. 
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/10c6119c-31be-481a-96c3-8a0a80963179)

2. When we are doing a comparison between a newly imported table and an existing table (Mark Differences between New and Old Data), the following error will happen,
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/adcd9837-c015-4179-8d3e-ba983116d63c)
 
3. A few times (I say a few times because it only happens twice for me and now I'm not able to replicate the issue), an error happens when we try to plot a country between old and new data,
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/9ed06e0c-d861-415b-bfb1-f69988178760)

If you want to run some tests, you can take the file attached here, 
[IFsDataImport.zip](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/12456603/IFsDataImport.zip)

**Comment by PardeeCenterIFs** [comment] 2023-08-28 20:18
I couldn't reproduce #1, it looks fine in my version, could it be the WDI update that I assume you have in your version?: 

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/33665510/6c6bc04c-8769-4e32-aa3c-5e1e4c4cde92)

**Comment by PardeeCenterIFs** [comment] 2023-08-28 20:28
On #2, I was able to reproduce it and fixed it, it'll be included in version 8.05, but I don't see anything marked, could you help me identify something that should be mark after running this option.

**Comment by PardeeCenterIFs** [comment] 2023-08-28 20:31
#3, I couldn't reproduce either, and it seems doesn't always happen for you, these are the types we need to record on video, in case it's a long path that takes you to the error:

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/33665510/009639b5-f12c-4c6a-bd48-2fa1053164ae)

**Comment by quciet** [comment] 2023-08-29 21:55
> I couldn't reproduce #1, it looks fine in my version, could it be the WDI update that I assume you have in your version?:
> 
> ![image](https://user-images.githubusercontent.com/33665510/263824367-6c6bc04c-8769-4e32-aa3c-5e1e4c4cde92.png)

It was reported by one of the RAs using another data update. I used this WDI update and saw the same problem. Is it possible that this is some bug being fixed from 8.03 to 8.04? I'm using 8.03

**Comment by quciet** [comment] 2023-08-29 22:00
> On #2, I was able to reproduce it and fixed it, it'll be included in version 8.05, but I don't see anything marked, could you help me identify something that should be mark after running this option.

Thank you so much! I'm not sure actually. The purpose of this function is to find a difference in values of same country-year between old and existing tables. I do believe Sudan or South Sudan, or Kiribati should have big changes.

**Comment by quciet** [comment] 2023-08-29 22:01
> I couldn't reproduce #1, it looks fine in my version, could it be the WDI update that I assume you have in your version?:
> 
> ![image](https://user-images.githubusercontent.com/33665510/263824367-6c6bc04c-8769-4e32-aa3c-5e1e4c4cde92.png)

Maybe it is just my version. I will try a new version later next time.

**Comment by solox1** [comment] 2023-08-30 14:35
Hi Yutang,

I see there's a couple of updates in the Vetting form from 8.03 to 8.04,
maybe that's what fixed it, but I don't think it was the same issue.

**Comment by PardeeCenterIFs** [comment] 2023-08-30 14:39
> > On #2, I was able to reproduce it and fixed it, it'll be included in version 8.05, but I don't see anything marked, could you help me identify something that should be mark after running this option.
> 
> Thank you so much! I'm not sure actually. The purpose of this function is to find a difference in values of same country-year between old and existing tables. I do believe Sudan or South Sudan, or Kiribati should have big changes.

Maybe I had taken this update before, because I don't see any differences in Sudan or South Sudan, at least for XDebt%GDP.

**Comment by quciet** [comment] 2023-10-09 19:38
I'm updating this thread so that all the issues related to data import & vetting are directed here.

**Comment by quciet** [comment] 2023-10-16 17:10
Hi there,

Another potential issue was found when we were importing the data,
IFs is filling in values for country-years that were originally blank (examples below). This issue occurs during importing (example below). The data is already blended so it’s not IFs blending data, it looks like IFs is interpolating/extrapolating data from one year to subsequent years that should be blank. Also, the most recent column was picking up values, but wasn’t always accurate. I attached the spreadsheet below used for data import, and you can see the resultant table would have some filled in values. For example, values of Albania in 1990-1994 were added by IFs.

[RoadsPaved%_OriginalBlended.xlsx](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/12919647/RoadsPaved._OriginalBlended.xlsx)

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/4199cd50-f10f-4374-9a82-291ccdf3a2e1)

Any idea? Thanks!

**Comment by PardeeCenterIFs** [comment] 2023-10-17 23:40
Hi Yutang, wow, I don't know how I didn't see this one before, it's basically taking the previous value instead of the nulls. I have fixed it and the fix will be included in version 8.09.

I'm going to close this issue, but you can open a new one if there's something pending from this long thread.

**Closed as completed by PardeeCenterIFs** 2023-10-17 23:40 UTC
Labels: Priority 5, Extended Features
