### ISSUE TITLE
year columns are not sorted

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#258] opened 2024-02-13 20:56 UTC
Hi there,

I think this is not a common case but the dataset is really giving me a hard time to import. Please look at the CarbonTot tab in the Excel file attached. What happened is that IFs correctly covered the data from long form to wide form, however, the columns of years are not sorted in the resultant table. IFs correctly extract the earliest and the most recent values from the first year and last year where data are available, but the order of year columns are wrong. 
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/eb8318e4-b557-45bb-8672-7f06df7f4300)

One additional problem I encountered with this dataset was that when I clicked on Excluded to see countries that have no matches in IFs, it threw an error, 
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/b75ca2c8-2eaf-4fdd-b02e-dc16bfe5e432)

 
[CDIAC_national_1751_2020.xlsx](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/14271973/CDIAC_national_1751_2020.xlsx)

**Comment by PardeeCenterIFs** [comment] 2024-02-14 20:54
First issue, related to the order of years, making sure years are sorted, that has been implemented now.

Second issue, logic is case sensitive, so it is possible that found countries are more than NR, since there could be some in uppercase and others in lowercase. We have increate the number of possible countries to NR * 2. This second issue is caused by countries like Germany saved both as Germany and GERMANY. Same for Sudan and Vietnam.

This fix will be included in version 8.18.

**Closed as completed by PardeeCenterIFs** 2024-02-14 20:54 UTC
Labels: Priority 4, Extended Features

**Comment by quciet** [comment] 2024-02-14 21:01
> First issue, related to the order of years, making sure years are sorted, that has been implemented now.
> 
> Second issue, logic is case sensitive, so it is possible that found countries are more than NR, since there could be some in uppercase and others in lowercase. We have increate the number of possible countries to NR * 2. This second issue is caused by countries like Germany saved both as Germany and GERMANY. Same for Sudan and Vietnam.
> 
> This fix will be included in version 8.18.

Thank you so much! Yes, I was guessing that different country names for the same country might cause the issue. This fix could be a big help as people can worry less about country concordance! 

BTW, a related question, does this mean that we have to make sure, in the long format of that country concordance table in IFs, there can not be any N to M match? Instead, we can only have 1 to N match for each country/region in IFs.

**Comment by PardeeCenterIFs** [comment] 2024-02-14 22:09
We can have N to M match, but if N * M > 2*NR, then we will get the error again. Unfortunately changing the size of the array dynamically was not working, not sure why, so I just brute forced it to 2*NR.
