### ISSUE TITLE
Power Contribution Display Error

### ISSUE THREAD

**Issue by A-pirzadeh** [PardeeCenterDU/IFs-Issues-Tracking#79] opened 2021-08-05 01:41 UTC
Nothing is populating for the Power Contribution page in IFs 7.70. 
Date Found: 8/4/2021
Found by Audrey Pirzadeh
![image](https://user-images.githubusercontent.com/83729959/128277609-b0c85f13-3050-4d38-b2d3-626322031256.png)

**Comment by PardeeCenterIFs** [comment] 2021-08-10 21:37
José: I can't reproduce this one, it seems to be working in version 7.71.

**Comment by PardeeCenterIFs** [comment] 2021-08-18 18:47
José: I'm closing this since during the modeling Pod Audry mentioned it wasn't a problem anymore, tested in version 7.72.

**Closed by PardeeCenterIFs** 2021-08-18 18:47 UTC
Labels: Bug, Priority 5
