### ISSUE TITLE
8.20 Education Quality Flex Display error

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#295] opened 2024-04-22 19:25 UTC
If I choose those lists and make a line graph it gives me an error

**Comment by PardeeCenterIFs** [comment] 2024-04-23 21:05
Couldn't reproduce, need more details.

**Comment by jonathandmoyer** [comment] 2024-04-23 21:28
[image: image.png]

Produces this error:
Server Error in '/ifs/ifsweb' Application.
------------------------------
*A potentially dangerous Request.Path value was detected from the client
(&).**Description: *An unhandled exception occurred during the execution of
the current web request. Please review the stack trace for more information
about the error and where it originated in the code.

*Exception Details: *System.Web.HttpException: A potentially dangerous
Request.Path value was detected from the client (&).

*Source Error:*

An unhandled exception was generated during the execution of the current
web request. Information regarding the origin and location of the exception
can be identified using the exception stack trace below.
*Stack Trace:*

[HttpException (0x80004005): A potentially dangerous Request.Path
value was detected from the client (&).]
   System.Web.HttpRequest.ValidateInputIfRequiredByConfig() +562
   System.Web.PipelineStepManager.ValidateHelper(HttpContext context) +54


------------------------------
*Version Information:* Microsoft .NET Framework Version:4.0.30319; ASP.NET
Version:4.8.9220.0
-----
  Jonathan D Moyer, PhD
  Assistant Professor
  Director
  Frederick S. Pardee Institute for International Futures
  Josef Korbel School of International Studies
  University of Denver

**Comment by PardeeCenterIFs** [comment] 2024-04-25 00:14
This seems like the same error we were getting with the poverty displays "<", unfortunately I can't see the image.png that you posted, for some reason, I only see the name of the file.

**Comment by jonathandmoyer** [comment] 2024-04-25 15:26
Yea, it seemed like the same error for poverty.  And these education
quality displays have an & in them, so I figure that's what's going on?  It
blows up if you pick afghanistan for education quality for any of the core
lists and try to make a line graph
-----
  Jonathan D Moyer, PhD
  Assistant Professor
  Director
  Frederick S. Pardee Institute for International Futures
  Josef Korbel School of International Studies
  University of Denver

**Comment by PardeeCenterIFs** [comment] 2024-04-26 19:25
The special character problem was solved in version 8.21, are you still using 8.20? 
I vaguely remember that when I first created 8.21 there were some special characters that were still problematic, so I redid the installation about 30 minutes after posting the first one. Can you check the timestamp of the zip file you download and see if it matches the one in our server.
Actually I see that the title of the issue says this is in 8.20 which is known.
Anyway, this seems to be working in my 8.21 version. I'll close the issue.

**Closed as completed** 2024-04-26 19:29 UTC
Labels: Priority 5
