### ISSUE TITLE
Initial Year Value of Exports and Imports Not Equaling Sector Sum

### ISSUE THREAD

**Issue by caleb-petry** [PardeeCenterDU/IFs-Issues-Tracking#171] opened 2022-03-17 16:21 UTC
I have encountered an issue with total exports/imports where the initial year value is not equal to the sum of the sectors. Instead, it is much higher. There are differences in later years though these are much smaller. I first noticed this issue with the India-USA and USA-India dyads. There is a graph included which shows the issue for the exports of the USA-Pakistan and India-Pakistan dyads:
 
![image](https://user-images.githubusercontent.com/7695597/158845544-80414c62-b9ed-41c3-b4e4-f3941cf8ec96.png)

This is coming from a version that has Jose’s fixes and my changes to influence. These are limited to the Influence subroutine besides the declaration of a couple variables. I attempted to recreate the problem in a 7.82 install and did not see the same behavior.

IFs Version: 7.82 VB.Net dev version with Influence changes

**Comment by caleb-petry** [comment] 2022-06-03 19:26
Increased priority because while it does not influence FBIC, it will likely be used alongside it.

**Comment by PardeeCenterIFs** [comment] 2022-06-03 23:16
I think I got it, there was a problem in the AdjustXDyadic procedure in .NET only, we were not reseting values to 0, so it was producing much bigger values. This should be fixed in version 7.85.

The line of code I added is the else branch:

If Not CXDYAD(keyi).ContainsKey(keyj) Then
        CXDYAD(keyi).Add(keyj, 0)
Else 'jrs 2022/06/03 it was not starting from 0, values previously inserted
        CXDYAD(keyi)(keyj) = 0
End If

![image](https://user-images.githubusercontent.com/33665510/171965392-b2587ea7-9d1d-40c1-a64e-d6fbb9d1f2b1.png)

**Comment by caleb-petry** [comment] 2023-10-09 22:40
This issue or a similar one seems to have reoccurred. Values in 2019 appear to be double what they should be when compared to later years and monadic trade in the initial year.

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/7695597/d7edbd73-6ae7-4141-ad95-70a6f59cf127)

Version: Install Version 8.07

**Comment by PardeeCenterIFs** [comment] 2023-12-08 19:40
This might be a display issue, because when I decompose Africa vs Angola, the issue is not there.

**Comment by PardeeCenterIFs** [comment] 2024-02-06 00:48
I think I got it Caleb, not sure why, but the bilateral logic was not deleting the values in the first year, so they were being duplicated when doing aggregations. This fix will be included in version 8.17.

**Closed as completed by PardeeCenterIFs** 2024-02-06 00:48 UTC
Labels: .NET Problem, New Issue / Not Under Review, Bug, Priority 4, Bilateral Interaction\Influence in IFs
