### ISSUE TITLE
SDG Graph vb 6 blow-up

### ISSUE THREAD

**Issue by jonathandmoyer** [PardeeCenterDU/IFs-Issues-Tracking#167] opened 2022-03-04 21:34 UTC
7.82:  Display, Specialized Display, SDG Graph, blowup

**Comment by PardeeCenterIFs** [comment] 2022-03-04 23:18
I couldn't reproduce this one, could you please trying clicking Russia, and from the context menu go to the SDG Graph, does it work then? I'm thinking maybe it has to do with the default country you have.

**Comment by jonathandmoyer** [comment] 2022-03-04 23:21
It may be that this was fixed?  I thought my version was 7.82 but it was
7.75.  It still blows up on 7.75 no matter what I do.
-----
  Jonathan D Moyer, PhD
  Assistant Professor
  Director
  Frederick S. Pardee Center for International Futures
  Josef Korbel School of International Studies
  University of Denver

**Comment by PardeeCenterIFs** [comment] 2022-03-08 21:40
I don't think this form has been changed since June 2020, that's version 7.53. I just copied the 7.75 files in my installation machine, and couldn't reproduce it either, maybe there's something wrong with your particular installation. I'm going to close the issue, and we can reopen it if we can reproduce in any other version.

**Closed by PardeeCenterIFs** 2022-03-08 21:40 UTC
