### ISSUE TITLE
Data Importing issues

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#252] opened 2023-10-26 22:00 UTC
1. The RA was not able to select a variable that has "&" in its variable name. In her case, the table was LandUrban&Built, the recording she did shows the problem.
https://www.loom.com/share/337ab778fb4042a190d4a51155fe547d?sid=37f84ec9-4f3d-4a08-bf12-6964678a9b61

2. After importing some tables, the process fails to store information in the DataDict table in the IFsDataImport. Not sure what caused the problem. There were 11 tables in total, but only 4 of their DataDict entries were saved. 

Thanks,
Yutang

**Comment by samimck** [comment] 2023-10-27 02:16
Regarding issue 2, IFs gave this error after clicking "Accept Data" during data import. The examples are for SeriesLandAgri and SeriesLandTotal. Similar errors were thrown for other related land series.
<img width="676" alt="LandAgriError" src="https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/149128484/4c7734e2-17a9-493f-90fc-ce42d9daab9f">
<img width="668" alt="LandTotalError" src="https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/149128484/09e3a6b9-da6a-45ec-b549-7d32c6e04dc0">

**Comment by PardeeCenterIFs** [comment] 2023-10-27 15:20
Can we include here the original Excel file to import the data and reproduce the error.

**Comment by samimck** [comment] 2023-10-27 20:14
> Can we include here the original Excel file to import the data and reproduce the error.

[LandAgri.xlsx](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/13192935/LandAgri.xlsx)
[LandTotal.xlsx](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/13192938/LandTotal.xlsx)

**Comment by PardeeCenterIFs** [comment] 2023-10-27 21:37
These 2 don't seem to have "&" in the name.

**Comment by samimck** [comment] 2023-10-27 21:48
> These 2 don't seem to have "&" in the name.

oops! here's LandUrban&Built.
[LandUrban&Built.xlsx](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/files/13193541/LandUrban.Built.xlsx)

**Comment by PardeeCenterIFs** [comment] 2023-10-31 22:23
I don't think the first issue was priority 5, there was a workaround by just scrolling down and clicking in the listbox box below. Anyway I think we should create items individually.

1. This one is fixed, but as I said there was a workaround by scrolling down and clicking directly in the list.
2. I have fixed this one, the problem was that the DataDict.db field "Name in Source" has double quotes in its content: Item "Agricultural land". I'm now handling those quotes.

Both fixes will be included in version 8.11.

**Closed as completed by PardeeCenterIFs** 2023-10-31 22:23 UTC
Labels: Priority 5, Extended Features
