### ISSUE TITLE
update values under MostRecent/Earliest columns

### ISSUE THREAD

**Issue by quciet** [PardeeCenterDU/IFs-Issues-Tracking#287] opened 2024-03-26 21:57 UTC
The 3 features under the extended features, which update values under either the earliest or mostrecent columns, are not working correctly. 

When we rebased our model's base year from 2017 to 2019, IFs ran an internal process that update the values under the MostRecent column, i.e., the feature highlighed in the screenshot below.
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/29c90ac6-8c20-407b-a923-d58f0e5ac015)

However, this process is not correctly storing data values, probably due to a conversion between data types. You can see the comparison below, the upper graph is prior to the conversion.

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/dcf5cb6b-5ad3-4645-8aae-1645f495184a)

![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/5f7bc2bf-a917-4f90-999c-0adbdd5b5035)

Then I tried to test this feature alone through Extended Features by manually changing a country's value under the MostRecent column in the database and then running the option, but IFs is not letting me. I'm using version 8.19.
![image](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/34465524/acef35ac-efbc-48ba-a5ec-0743ac9a0b08)

**Comment by PardeeCenterIFs** [comment] 2024-03-27 14:15
The blow up error was caused by an empty string inserted in a table, SeriesEdPriAdultGrads15Total% has "" instead of a Null in 2015 for the DRC.

The extra decimals were caused by using the Real type to pass the values to update SQLite, it was fixed by using Text parameters instead. The fix will be included in version 8.20.

**Closed as completed by PardeeCenterIFs** 2024-03-27 14:15 UTC
Labels: Priority 5, Extended Features
