### ISSUE TITLE
8.21 Server Error

### ISSUE THREAD

**Issue by tblanga** [PardeeCenterDU/IFs-Issues-Tracking#294] opened 2024-04-20 20:07 UTC
After downloading, installing, and opening 8.21 through a desktop shortcut, this is the error that appears. I've uninstalled and reinstalled 8.21 twice to make sure it wasn't a one-off issue.
![Screenshot 2024-04-20 134244](https://github.com/PardeeCenterDU/IFs-Issues-Tracking/assets/103873298/5df4c935-0bf2-49d0-9802-2c1f5c10d722)

**Comment by quciet** [comment] 2024-04-23 17:29
@solox1 Hi José, I do believe this one was caused by an incomplete uninstalltion of IFs. So if you did not fully uninstall IFs and then install another one, this could happen. But I wanted to double check with you. Thanks!

**Comment by PardeeCenterIFs** [comment] 2024-04-23 21:11
It could be Yutang, it hasn't happen to me, but it's very likely that's the reason.

**Comment by quciet** [comment] 2024-04-24 19:20
> It could be Yutang, it hasn't happen to me, but it's very likely that's the reason.

Cool. I will close this one. Another student just reported the same problem, and she did not fully uninstall the previous version of IFs before installing a new one.

**Closed as completed by quciet** 2024-04-24 19:20 UTC
Labels: Priority 4
