### ISSUE TITLE
Windows 11 validation

### ISSUE THREAD

**Issue by PardeeCenterIFs** [PardeeCenterDU/IFs-Issues-Tracking#92] opened 2021-10-08 21:12 UTC
Let's start by trying to install a target version of the vb6 version, and then the .NET version. Test Basic Display, and create a simple scenario, and run the model.

Second let's try creating a development machine, and do the same tests.

We will need a target machine for these testings, can we ask UTS?

**Comment by Coryv221** [comment] 2021-11-12 17:35
<html>
<body>
<div data-ogsc="rgb(0, 0, 0)" data-ogsb="rgb(255, 255, 255)" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; background-color: rgb(255, 255, 255) !important;">For the testing, I loaded IFs, created one of each graph type available from Flex-Displays, using the world as a single, and disaggregated, group, and then ran a scenario build to 2100 with the C19NoCovid scenario component. Basically, a full effort to make it break under circumstances that IFs works fine with on our current machines. This was done with 7.79 Beta and 7.58 for VB6 and .NET respectively.</div><div data-ogsc="rgb(0, 0, 0)" data-ogsb="rgb(255, 255, 255)" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; background-color: rgb(255, 255, 255) !important;"><br aria-hidden="true"></div><div data-ogsc="rgb(0, 0, 0)" data-ogsb="rgb(255, 255, 255)" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; background-color: rgb(255, 255, 255) !important;">Below are the main results of that work:</div><div data-ogsc="rgb(0, 0, 0)" data-ogsb="rgb(255, 255, 255)" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; background-color: rgb(255, 255, 255) !important;">

  | Virtual Machine Results
-- | --
Running IFs, VB6 | No issues came up. Worked as expected
Running IFs, .NET | Worked the exact same as on Chrome on Windows 10 (this was expected)
Developing IFs, VB6 | After a 40+ minute hitch installing VB6 from our shares drive resources, everything loaded and I was able to do edit and run IFs. The hitch is on the second to last step, and it's unclear why it is happening. It happened on all of five attempts to install, on the same step, regardless of install settings, admin privileges, or resources allocated to the VM. This suggests we could keep using VB6 with Windows 11, but it will be inconvenient to do the install, however, there were reproducibility problems on the native machine (see below).
Developing IFs, .NET | Worked exact same as Windows 10. This was expected because all our development environment is supported by Windows 11, officially.

<br aria-hidden="true"></div><div data-ogsc="rgb(0, 0, 0)" data-ogsb="rgb(255, 255, 255)" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; background-color: rgb(255, 255, 255) !important;">I want to also note why the laptop is probably not the cause of the issues because it does meet the minimum hardware requirements for Windows 11 by a large margin, despite its age. The only hardware it doesn't have, that Windows 11 expects, is a TPM (which I have forced a workaround so Windows shouldn't be using that as a factor at all, and there is no reason the absence of a TPM would be why Windows 11 is having issues). However, it is much slower than my VM in terms of hardware, across the board. Therefore, it maybe that this hitch I experience in both cases is a result of some process that is getting locked and must be brute forced in an ultra-inefficient way (because of some unknown difference between 10 and 11) and letting the laptop sit for several more hours could have been the solution. It's hard to know without testing on another, faster, machine.</div><div data-ogsc="rgb(0, 0, 0)" data-ogsb="rgb(255, 255, 255)" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; background-color: rgb(255, 255, 255) !important;"><br aria-hidden="true"></div><div data-ogsc="rgb(0, 0, 0)" data-ogsb="rgb(255, 255, 255)" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; background-color: rgb(255, 255, 255) !important;">I have the following conclusions, based on the above:</div><div data-ogsc="rgb(0, 0, 0)" data-ogsb="rgb(255, 255, 255)" style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; background-color: rgb(255, 255, 255) !important;"><br aria-hidden="true"></div><div style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 15px; line-height: inherit; font-family: &quot;Segoe UI&quot;, &quot;Segoe UI Web (West European)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div data-ogsc="rgb(0, 0, 0)" style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: rgb(0, 0, 0) !important;"><ol><li>It is not recommended to install Windows 11 on any machines that will be used for IFs development. Windows 10 will be supported until October 2025, so there shouldn't be any security concerns on that front.</li><li>For end-users, there is no reason to be worried that their IFs will stop working if they upgrade.</li><li>I think additional testing on more modern equipment is needed. I want to eliminate any chance that the hardware of the laptop I used is why any problems came up, because that may resolve this issue.</li></ol></div></div>
</body>
</html>

**Comment by Coryv221** [comment] 2021-11-19 16:43
From continued testing, all issues with VB6 install are resolveable by re-running the install and following instructions in provided installation documentation. It may need to be re-run several times, but it will install on a Windows 11 machine

**Closed by Coryv221** 2021-11-19 16:43 UTC
Labels: New Issue / Not Under Review, Priority 5
